basePath: /
definitions:
  gin.H:
    additionalProperties: true
    type: object
host: localhost:8080
info:
  contact:
    email: davidasb.developer@gmail.com
    url: http://www.swagger.io/support
  description: Simple transactions API to handle CSV files and Emails.
  license:
    name: license(Mandatory)
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Personal Transactions API
  version: version(1.0)
paths:
  /create-account/:
    post:
      consumes:
      - application/json
      description: creates an account based in email and full name
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Full name
        in: body
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          description: 'status": 200, message: "Account created", data: models.Account{}}'
          schema:
            $ref: '#/definitions/gin.H'
  /send-email/:
    post:
      consumes:
      - application/json
      description: Sends an email from an account
      parameters:
      - description: Email
        in: query
        name: email
        required: true
        type: string
      responses:
        "200":
          description: 'message": "Email sent"}'
          schema:
            $ref: '#/definitions/gin.H'
  /upload-transactions/:
    post:
      consumes:
      - multipart/form-data
      description: Adds transactions to the database from a csv file
      parameters:
      - description: transactions
        in: formData
        name: transactions
        required: true
        type: file
      - description: account_id
        in: formData
        name: account_id
        required: true
        type: string
      responses:
        "200":
          description: 'message": "Transactions successfully uploaded and saved."}'
          schema:
            $ref: '#/definitions/gin.H'
swagger: "2.0"
